# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: America/Edmonton

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: KNES 381 Final Project # the main title

tagline: Welcome! # it will display as the sub-title

description: >- # used by seo meta and the atom feed
  This is my KNES 381 Final Project

# Fill in the protocol & hostname for your site.
# e.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://alishaparmar11.github.io"

github:
  username: alishaparmar11 # change to your github username

twitter:
  username: twitter_username # change to your twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Alisha Parmar
  email: alisha.parmar14@gmail.com# change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://www.linkedin.com/in/alisha-parmar-a362811bb/
    - https://github.com/alishaparmar11 # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

google_site_verification: # fill in to your verification string

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

google_analytics:
  id: # fill in your Google Analytics ID

goatcounter:
  id: # fill in your Goatcounter ID

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode: # [light | dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn:

# the avatar on sidebar, support local or CORS resources
avatar: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAQEBAQEBAWEBANDQobDRUVDRsIFQ4WIB0iIiAdHx8kKDQsJCYxJx8fLTstMStAREMwIytKQDtANzQ5REABCgoKDg0OFQ0NFTcZFSUrKzc3NzcrKy03LS0tKzctKysrLTcrLS0rLS0tLSsrKy0tLSsrKysrKysrKysrKysrK//AABEIAMgAyAMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAEAAIDBQYBBwj/xABFEAABBAAEAgUIBwcCBQUAAAABAAIDEQQSITEFQQYiUWFxEzJTgZOhsdEUI1JikcHwBxUzQnPh8RZDgoOSosIkJVRjcv/EABkBAAMBAQEAAAAAAAAAAAAAAAABAgMEBf/EACIRAAICAgMAAgMBAAAAAAAAAAABAhEDIRIxQSJREzJhQv/aAAwDAQACEQMRAD8A1zcHB6GP2TfknfRIPQR+yb8kEMQpBP3rto5bC24OD0Efsm/JTPwWGr+BH7FvyQLZlOya0qQ7GS4LD8oY/ZD5JjOGxehZ7IfJWEMQdsjGxAbo0BQv4fF6GP2Q+ShdgovQs9kPktBLAOSClh7k9C2VDsFF6Jnswo/oMXomezCsCwKRmHtGgsq/oEXomezC6MBF6Jnswrg4RDviRodgP0GL0TPZhPbgIvRM9mERkXaSCwX6HD6JnswnNwMPomezClISaigsnh4bBzij9kEbFwzD+hiP/KafyQkbip2PPak0Fh8fB8Of9iL2LfkpxwbDbfR4vYt+SGhnPajG4k0s2i7IhwbDA/wItf8A6W/JOHAoP/jxexb8l1syOw0ubRS9FLYGzgGGIP1Ed/0W/JMbwLCgHNBHf9FvyVy1haNNVx9ubtqpUhtGdbwuBpdUMY6kg/hAcvBJEyHrOH3HpLUzMY6MhcAKvjh2lI4JpW1mVFKwlFRX2Iv6IAiYGAIKOYGSiLVjI4FMjy9ilzN7FIAzpKQ08hOyMkIULmIQADYjaIAIU5bWymawu0pAURRydqjkjvYKwiwY5rk7K2CVjKp0VKJ7EbMChnqhAjwmhSvCiLCkBIHhPMwQwjKkGHKAJGYlHQYm9Cq0QKRjaSoZahwU0U1KsYT2p7ZEnEdmgws5cjY6pZqHFlqlHEjW6yeNmimg/FYc5ieRa5JAR8ScbB5Mf8Ek0miW0BuiIUechFZjzTCAtzMhzErmYhTOi7FE9hQA5sqeZCgiwhEQMvdADzIU9knameS1U4w+yAOxvCLjmCDdBSquO8X+jsAbq+Q0wb6qXSVjSvo0OIxrWMc9xoNaSVl5umEZtzQ54bfmkFefYvjeNxz5II3uMeZzZHaRtPbtyU3DOjAwwcBITnyl3iP0fxXPPMkdUMDas9D4dx+GcW1x5aOGUhWD2A6heZYJxicWE2XNGo01oWfz9S03R/jtUyQ207O2rxTx5t0ycmGujQOiXBEiyQdeSbYXQc5CMOpBEk6RMzd6BDH6aUmtZe6c5/anNcEAPbhuwqGWJw5IkSUn+WB3SGAtJUhZpoiCWlR5L2QBHBu7+nJ8ElLHhHWaNWHDtXFNjoJNKF4SY/Sk4H1qyRrSk94T9OajlewGiQCgDoIO4XXsHJdbECLBSEJHNAEdkKaOVP8AJmtQofIO5J9gwrOCCvM+m2MrFMdygDjl9dX+S9BeHAE1yK8Z6U47NjHAmw4vB7xqPksc2lRtg27NFwHDtijAj1DrIPaj5ngAkm6vbVY3BY97ogxrskZbTnXlcTW47KRvR6fNKIQ8PYcwJD89Lz5RfZ6kZeEWL4kHSAhjm5XDfq5h/i1ZQOsGtXNJIIOjxz/XaFW8b4DiC8iM00700PPvSw3DsVhm5iDIxutA9Zg/XJWpKjOWOV9G86N8U2iebaaDDd5T2FaR0a8q4bxAZmvYbY47eaR2hepcIxYlYLNkAUebhyXViyeM4suP/SGmMqJ8ZCtSQoJdVvyOeitLCuA0ipWcwoq7lQhgnXDKkWnsThGkA0SpzZjyU0TRsQlJGBskMkjxZ5pKC0kqQWDRYgO2danbIVh34pzJba6hm1C0kXFmEDwCcc0X2VkwSjVC4riHZqDiNFVCRzySSSW96nx+JDnW0ckJh5bJoDcd6iUreiaa7C2Y2RpADjSusDxTk4qneRmG2wTPKZXDS7tFga2PGg7FTMxKzeBl1OugVtG61rFKSJboMxuMa2J7iQA1jze3JfOfHsSDLI8G9aYd+d38F7b0sd/6OarssI06trwnEMdJnFUGh2y5837JHTg3GzQdGOF/S8M1uaspOYcj4rRw4KLBAdYEtBOgoacgFlOgmP8AJF8d+eLZ4jdabFzkDOWF5do0BuYH5LinfKj08XHin6WmH4m7EUGtAzA5jZY5vqUsT5WuLHEPBuiqnBEg9d1XXVaMgHr5qxn8hB9aQ4OLd83lD7ypaRq20ZjFQGJ8hZoBO4gdml/NbTo/xMsyG9Dl/AqicY3ROl5PLvJ2MrieZKfFMcpy6ZTCG960UjjlFNs9Sw04eARranruWT4FxWiI36adU9oWmZiwN12Qk5LRw5I8WPfh75LgwaeziDVMziDE3yXhK4sEdhwoXQK1bjY+5J00Z5JcmvB8UVrcMeRT/oTjzRoezsT2St5Jc2NRQA3hbikrVs6SnnIOCPEMfMM5KE/e7hQb26qXFgHNZ2BrkqBkZBNXqdFKTbN5zTSo2WGxbnC+0G0uHPOZ9ciqbBY8RNyvBcRzGqmwXHYrOU1bgOxaI53susTO/OBfYjCx2YUNCFUYvFMLwQdRlJREXHYy8AO2AFUmTTLvDGma7rsuMe2spsaID95RiNxc7YFNwT/KRnLre3NClWwUbLTimJ8phnB3PT3LzmThwjje6qJa4n8HH5fitziOqwNcazeaCatZjicmZk7eQZG0eJOvwXPOfJnZjx0jznA4zyMpd2F3dqtzwfpA2QAtP/6aTRCw/EcOGixzc61Dwt1Ss5Bxo8kTgpKx48ji6PWYuKwjXKAVT8Z4uHNLd3OOv3QgIcMe0n1qPER5TdbA91rnitnU5Og1mKLwBs0Af8Iv5Il0hZTicoY4HtvX+yrsNhy6NuUnrHrHKXZQOWgRjpCZmMfo0vZQr7xWtGKZp+HgyEMG5DS0E5Hdtg9q2HAcQSwtlHXjNEnTMF53M7JMy3EOdICdarq7e5aP6e5rTl1P8x21VYnTM8qtG18nEeS6IYlgf33LsLsd6Z+9Z3OGjgAujmcvA9EEEa67ybRZNBYpvG5NGgGyncR4lIYyDV809P0VNeGt+mYevPH4p8OOw5HnjXvXnkYzNBDtSF2WCWJoe6qFJV/R3/D01pZuCkvPD0wDQABZAC6lxX2Fv6KOUNlvQDsCGdh4m0D81AMHLnBjJ7xuu4zDvZZdvRu1lxl3YWurHOwbHXkduNt0L+5pGlv1ZAc9vW3AWm6B8NZMDK8igTS1+O4a3ybgwg7EDdXFP0LRTQ9FGNYH5wSGtJCpcRw6PO57K5IjieLxQfcbqYG05u6qJsWI2h0jq+1rSphRoB0Ye6KxRzCzaFw+Cmw2pFb5a1TuD9NsKQGPeW1pqatXeB4hFiH005mjbmEVYKTWzM8UxRay6JeSMxyluvILM8QdkZlJt7nB0p5aDZbrpzh8rI5GjRufMdgDpRPvXnmINtJ3Lsy5pqpUdkHcbMxPEXtrmAw+OmqGMBaGO5hzVcvZQY8btMjXerZOxUGYaaWATzWqkZuPpfcNkzMaRzAUmLZoT2IfgGHcGUQaHrVtNhS5tAHXuXK18jqX6mVlLnuyhvnu3Li4Ac67FNw/M1zHkXGKqzRHYrmeCKA/XAkiN1NbXPQ2VBi8YwRRU3qB4sbaV/da34ZLbDsawyjyrDZa4Ec+X6C0fAZI5WsLrpwo/dKyPC80Elh4MTxbb0Dx860Wm6O+SzgsOVpdZaf5bUXT0XxtGmPRyMGxdlSDgoV5A4OaKNp5C61K0cDVMopOAM0IQ+P6OirBNlaUpsqYjGHgDhqCVJiuDSSNDcxrRavKnNZt6kwMT/oY6EOPxSXobAuKCqPOWMygEgg0LNKt424SMc0Ak
# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
social_preview_image: # string, local or CORS resources

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  active: # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development | production]

pwa:
  enabled: true # the option for PWA feature (installable)
  cache:
    enabled: true # the option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

paginate: 10

# The base URL of your site
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
